ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight_kg DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hydration_goal_ml DOUBLE PRECISION;
ALTER TABLE daily_logs ADD COLUMN IF NOT EXISTS water_ml DOUBLE PRECISION;
